### ISSUE TITLE
Warehouse not displaying the books

### ISSUE THREAD

**Issue by lucacontalbo** [ilmercatinodellibro/ilmercatinodellibro#100]
I'm using the server at www.ilmercatinodellibro.com with the admin account.
I've seeded the db as described in the README files. The "Catalogo" section correctly shows the books that we can sell, as well as their availability.

![Screenshot from 2024-06-25 19-58-16](https://github.com/ilmercatinodellibro/ilmercatinodellibro/assets/37805862/8f2ac2cb-627a-4f10-a464-34fcbfe8b152)

but when trying to visualize the books in "Magazzino", the page is empty. I've tried with different filters but nothing changed.

![Screenshot from 2024-06-25 20-00-34](https://github.com/ilmercatinodellibro/ilmercatinodellibro/assets/37805862/5010c19f-d932-4a1d-9798-e99de2113959)

How can I fix this?

**Comment by IlCallo** [comment]
This seems to be due to an error in the seeding command which sometimes generates invalid data
I'll check out the seeding command later, avoiding the seeding and manually adding data avoids this kind of issues AFAIK

**Comment by IlCallo** [comment]
Fixed via 8f00b93fdaffaa8e5164f273b19a8a1771b73ca0 and later commits
