### ISSUE TITLE
Cannot add new books in the warehouse

### ISSUE THREAD

**Issue by lucacontalbo** [ilmercatinodellibro/ilmercatinodellibro#101]
I'm using the server at www.ilmercatinodellibro.com with the admin account.
When I try to add a new book, it throws an error.

![Screenshot from 2024-06-25 20-03-43](https://github.com/ilmercatinodellibro/ilmercatinodellibro/assets/37805862/59ce6c49-b128-44c1-a35a-b89ee9984922)

![Screenshot from 2024-06-25 20-03-53](https://github.com/ilmercatinodellibro/ilmercatinodellibro/assets/37805862/7ea6e66a-443f-4cff-a98a-c57738ff7b76)

How can I fix this?

**Comment by IlCallo** [comment]
Fixed, there was an issue with the receipt template localization
