### ISSUE TITLE
Problems while selling books

### ISSUE THREAD

**Issue by lucacontalbo** [ilmercatinodellibro/ilmercatinodellibro#102]
I'm using the server www.ilmercatinodellibro.com with the admin account.

I'm able to request new books, book them and add them into the cart. Once I get there, if I try to sell, it opens 2 contradicting modals as shown in the image

![Screenshot from 2024-06-25 20-10-04](https://github.com/ilmercatinodellibro/ilmercatinodellibro/assets/37805862/9dd73e3c-64d0-4a05-aca4-7b8f408471fb)

Is it possible to fix this?

**Comment by IlCallo** [comment]
This was probably due to the receipt generation and sending problem, gonna close this one
