### ISSUE TITLE
Duplicate books when selling

### ISSUE THREAD

**Issue by lucacontalbo** [ilmercatinodellibro/ilmercatinodellibro#103]
[to reproduce] i'm using the server at www.ilmercatinodellibro.com with an admin account.

When I try to sell a book, it shows me duplicate entries of the same book

![Screenshot from 2024-06-25 20-14-00](https://github.com/ilmercatinodellibro/ilmercatinodellibro/assets/37805862/444b52f6-6b39-4232-ab94-c30867bf008e)

Is it possible to fix this?

**Comment by IlCallo** [comment]
This was due to the seeder duplicated data probably, let's see if this happens again
