### ISSUE TITLE
Statistics page shows number of people as euros

### ISSUE THREAD

**Issue by lucacontalbo** [ilmercatinodellibro/ilmercatinodellibro#107]
![Screenshot from 2024-06-26 19-19-10](https://github.com/ilmercatinodellibro/ilmercatinodellibro/assets/37805862/35bc9b2a-8df2-4e0f-9c17-eceb4159153f)

**Comment by IlCallo** [comment]
That's because we see our clients as moneybags 🤑 

I fixed it already, but didn't re-build the client
