### ISSUE TITLE
Check how "reso" works: there are problems with some queries that take in account "reso" books

### ISSUE THREAD

**Issue by sarapeddy** [ilmercatinodellibro/ilmercatinodellibro#115]

**Comment by IlCallo** [comment]
Book which has been refunded: santiz71@yahoo.it

ISBN: 9788849420883

Book code: 0466/004

**Comment by IlCallo** [comment]
Seems like I managed to fix this with https://github.com/ilmercatinodellibro/ilmercatinodellibro/commit/cda769c4f563cf03155c9a1a0c2f60d6d841fb7c
