### ISSUE TITLE
Control the utility of search bar for ISBN in the cart. It isn't clear for what can be used here.

### ISSUE THREAD

**Issue by sarapeddy** [ilmercatinodellibro/ilmercatinodellibro#130]

**Comment by IlCallo** [comment]
It's not a search bar, it allows you to directly add a new book into the cart by ISBN
Or at least, it tries to, if there's any available book copy of that book

It's a shortcut to avoid exiting the cart, entering the requested or reserved dialog, adding the book and then moving it to the cart from there
