### ISSUE TITLE
Purchase and sell rate shouldn't be readonly

### ISSUE THREAD

**Issue by IlCallo** [ilmercatinodellibro/ilmercatinodellibro#47]
![image](https://github.com/ilmercatinodellibro/ilmercatinodellibro/assets/10036108/1b4749b3-b24c-4d6e-83ed-2903ff2a5f5e)

Into the setting dialog, purchase rate and sell rate shouldn't be readonly
We defined that they should be readonly when the mercatino is open, but we can drop that requirement if it's too complex to implement

**Comment by SirAuron** [comment]
We agreed with Sara that we will allow edit of those setting regardless of the period. Main difference it that before updating those values, the Admin will be prompted a confirmation dialog.

**Comment by andrea-cerlini** [comment]
Fixed in #54
