### ISSUE TITLE
Import books should support incremental upsert of books

### ISSUE THREAD

**Issue by IlCallo** [ilmercatinodellibro/ilmercatinodellibro#49]
The import books command currently doesn't support upserts of books, which is mandatory since the school ministry publish books list incrementally

Postgres `COPY` command doesn't support ignore on existing as MySQL does, but we are already filtering the CSV rows before using the `COPY` command, so we should just filter out the books for which ISBN + school code pair already exists on the DB

This will have consequences on the school import too

**Comment by SirAuron** [comment]
Should be resolved by [this commit here](https://github.com/ilmercatinodellibro/ilmercatinodellibro/commit/a4f01c6e16488bed01f1c9122a80c1fe802cc9d1).
