### ISSUE TITLE
Avoid displaying books without book copies in warehouse "order by ISBN" table

### ISSUE THREAD

**Issue by IlCallo** [ilmercatinodellibro/ilmercatinodellibro#51]
When using `order by ISBN` function in the warehouse, all books are shown, even if they don't have book copies
Books with 0 book copies should be filtered out from that table, their data shouldn't be downloaded at all if possible

**Comment by andrea-cerlini** [comment]
How will the "Presenti" filter for this table work after making this change?
![image](https://github.com/ilmercatinodellibro/ilmercatinodellibro/assets/84905818/4d0fa182-9f82-457b-a94c-3de5b9fbf97f)

**Comment by IlCallo** [comment]
You can have one or more book copies per book and each of those copies can have a different status

If you have 2 book copies and 1 of them isn't reserved nor sold, you'll use that filter to only show those ones

That's a totally different scenario from not having book copies at all, and if you filter using "Presenti" option you should still hide the rows of books which wouldn't have any related book copies

**Comment by andrea-cerlini** [comment]
Fixed in #54
