### ISSUE TITLE
All tables overflow hiding important columns

### ISSUE THREAD

**Issue by IlCallo** [ilmercatinodellibro/ilmercatinodellibro#52]
All tables (catalog, warehouse, etc) overflow, hiding actions column which is the rightmost one
Some other really important columns are on the right

Limit the width of the author, publisher and subject, with ellipsis and tooltip on hover to show the full content, to make all columns always visible

Title should be limited too, but it's more important, so it should have more space than author and subject column

If possible, define the column width using percentages of the available space

Keep `ISBN`, actions, status and prices column always fully visible
If this is unfeasible, make these columns sticky and all others scrollable

**Comment by andrea-cerlini** [comment]
Fixed in #54
