### ISSUE TITLE
Password field error overlaps with password security gauge

### ISSUE THREAD

**Issue by IlCallo** [ilmercatinodellibro/ilmercatinodellibro#57]
![image](https://github.com/ilmercatinodellibro/ilmercatinodellibro/assets/10036108/1ebbe969-60a5-4a13-a09c-83a87c88463f)

Not prioritary

**Comment by andrea-cerlini** [comment]
This component isn't present in the updated mock-ups, will update them in the next PR

**Comment by andrea-cerlini** [comment]
> @andrea-cerlini keep the password strength component anyway please, even if it's not in the mockups
> 
> We need to fix this for Coralloy template and Koioty anyway

Do we need to keep the component in the view or are you just saying to keep it into the codebase?

**Comment by IlCallo** [comment]
In the view, keep using it
