### ISSUE TITLE
Persist the language selection even after logout

### ISSUE THREAD

**Issue by IlCallo** [ilmercatinodellibro/ilmercatinodellibro#63]
If someone logs in, switch the language, then logout and refresh the page, the language preference is lost
This is tied to the LocaleStorage cleanup upon logout I guess, and related to adding the language switch for guest mode too

**Comment by andrea-cerlini** [comment]
I tried many times to reproduce the issue following the steps you described, but I couldn't get the language selection to desync... Can you explain if there were any other steps to this?

**Comment by yusufkandemir** [comment]
I noticed this issue before and fixed it here: https://github.com/ilmercatinodellibro/ilmercatinodellibro/commit/cf133bb9de19631ff8157043dd7cf3c4e345fd07
It has been merged slightly after you reported it.
