### ISSUE TITLE
Update the description into the page to check ISBN

### ISSUE THREAD

**Issue by IlCallo** [ilmercatinodellibro/ilmercatinodellibro#65]
It's a bit too general, it should specify that it's only used to verify if the book is good or not, but then you need to bring the books into the retail location

![image](https://github.com/ilmercatinodellibro/ilmercatinodellibro/assets/10036108/34307aa7-3242-444c-8da5-f154fd3b4297)

**Comment by SirAuron** [comment]
Closed by #80
