### ISSUE TITLE
Wrong button label

### ISSUE THREAD

**Issue by IlCallo** [ilmercatinodellibro/ilmercatinodellibro#68]
![image](https://github.com/ilmercatinodellibro/ilmercatinodellibro/assets/10036108/0dff726e-60ba-43d7-849e-b8ff943e74c2)

Into users "reserve books" page, the search button label is "add book", instead of "search"

Also, when searching the content of the search bar is cleaned up, which is a weird behaviour

**Comment by SirAuron** [comment]
Closed by #80.
Also since the Search button did not exactly made sense there, we removed it.
If not clear for the user, it can be re-added.
