### ISSUE TITLE
Filter by school and classes options order is in insert order

### ISSUE THREAD

**Issue by IlCallo** [ilmercatinodellibro/ilmercatinodellibro#72]
Is it possible to return at least classes in alphabetical order?
And possibly writing the name of the school near the class when selecting more than a school, in case of duplicate classes names

Also, it's not clear if the schools and classes filter is done with an OR or AND
I'd expect it to be an OR, but with some combinations we get no results at all

![image](https://github.com/ilmercatinodellibro/ilmercatinodellibro/assets/10036108/4cc13b31-970f-4091-9852-a7578e275ff0)

**Comment by SirAuron** [comment]
Closed by #80.
Order was changed to be like this.
![image](https://github.com/ilmercatinodellibro/ilmercatinodellibro/assets/30588533/4c3cbd57-8d7f-4896-822e-b3bb1c4c9736)
Also specifying the school address is somewhat mandatory because within the same province there can be more than one school having the same name.

**Comment by SirAuron** [comment]
@IlCallo now the question here is: how do we sort these classes? By one school first or by class first and then school name?
I'd say by School first.
Please @andrea-cerlini let's see here what Callo's suggestion will be.

**Comment by IlCallo** [comment]
@andrea-cerlini @SirAuron 
School first, then class, but keep the class before the school in the option label

E.g.

  - 1 A - School 1
  - 1 B - School 1
  - 1 C - School 1
  - 2 A - School 1
  - etcetc - School 1
  - 1 A - School 2
  - 1 B - School 2
  - 2 A - School 2
  - 2 B - School 2
  - etcetc - School 2
