### ISSUE TITLE
"Receipt of Registration" doesn't make sense

### ISSUE THREAD

**Issue by IlCallo** [ilmercatinodellibro/ilmercatinodellibro#75]
The receipt for books given to the retail location shouldn't be called "registration"

**Comment by SirAuron** [comment]
~~Closed~~ Should be closed by #80. Now the receipt is called withdrawal (ritiro).
Please check this out and see if this is correct @IlCallo .

**Comment by IlCallo** [comment]
Can't test this, but the fix seems fine to me
