### ISSUE TITLE
Users and role management should work in a different way

### ISSUE THREAD

**Issue by IlCallo** [ilmercatinodellibro/ilmercatinodellibro#77]
I have no way to downgrade an operator to user level
I guess "remove user" does that, but the wording there hint at the user being completely removed from the platform

An users shouldn't be able to change its own role

I'm not sure, but I'd disable the possibility to give admin role to other people for now

I'd expect an user to be automatically promoted to be operator when inserting it's email, or even provide a select with currently registered users
Invitation flow is broken anyway, so we can't test what's happening there

**Comment by andrea-cerlini** [comment]
Fixed in #87
