### ISSUE TITLE
`my-data` should be accessible to operators and admins too

### ISSUE THREAD

**Issue by IlCallo** [ilmercatinodellibro/ilmercatinodellibro#82]
Right now it's accessible only if you know the URL, it must be visible on the drawer for all users

**Comment by andrea-cerlini** [comment]
> Right now it's accessible only if you know the URL, it must be visible on the drawer for all users

Wouldn't that make this button here redundant?
![image](https://github.com/ilmercatinodellibro/ilmercatinodellibro/assets/84905818/99b1f68a-4246-433d-b916-fc79b365ac7c)
Because currently what it does is opening a dialog to edit the operator/admin's user data

**Comment by IlCallo** [comment]
Didn't notice that, but in that case you'd miss the actions in my-data page

![image](https://github.com/ilmercatinodellibro/ilmercatinodellibro/assets/10036108/543c1538-c3cd-485c-93c9-7c1b25a05afb)

Ask Nick which would be the best solution, I'd just keep the same UX for both Users, Operators and Admins

**Comment by andrea-cerlini** [comment]
Fixed in #86
